portfolio_/developers/urls.py
from django.urls import path
from . import views

app_name = 'developers'

urlpatterns = [
    path('', views.developer_list, name='developer_list'),
    path('add/', views.add_developer, name='add_developer'),
    path('<int:pk>/', views.developer_detail, name='developer_detail'),
]

portfolio_/portfolio_/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('developers/', include('developers.urls')),
]

portfolio_/developers/models.py
from django.db import models

class Programmer(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    age = models.PositiveIntegerField()
    language = models.CharField(max_length=100)
    framework = models.CharField(max_length=100)
    experience = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.name} {self.surname}"


# Create your models here.

portfolio_/developers/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Programmer

def developer_list(request):
    programmers = Programmer.objects.all()
    return render(request, 'developers/developer_list.html', {'programmers': programmers})

def developer_detail(request, pk):
    programmer = get_object_or_404(Programmer, pk=pk)
    return render(request, 'developers/developer_detail.html', {'programmer': programmer})

def add_developer(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        surname = request.POST.get('surname')
        age = request.POST.get('age')
        language = request.POST.get('language')
        framework = request.POST.get('framework')
        experience = request.POST.get('experience')
        
        Programmer.objects.create(
            name=name,
            surname=surname,
            age=age,
            language=language,
            framework=framework,
            experience=experience
        )
        return redirect('developers:developer_list')
        
    return render(request, 'developers/add_developer.html')

portfolio_/developers/templates/developers/add_developer.html
<!DOCTYPE html>
<html>
<head>
    <title>Add Developer</title>
</head>
<body>
    <h1>Add Developer</h1>
    <form method="post">
        {% csrf_token %}
        <label for="name">Name:</label>
        <input type="text" name="name" required><br>
        
        <label for="surname">Surname:</label>
        <input type="text" name="surname" required><br>
        
        <label for="age">Age:</label>
        <input type="number" name="age" required><br>
        
        <label for="language">Language:</label>
        <input type="text" name="language" required><br>
        
        <label for="framework">Framework:</label>
        <input type="text" name="framework" required><br>
        
        <label for="experience">Experience (years):</label>
        <input type="number" name="experience" required><br>
        
        <button type="submit">Add Developer</button>
    </form>
    <a href="{% url 'developers:developer_list' %}">Back to Developer List</a>
</body>
</html>

portfolio_/developers/templates/developers/developer_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Developer Detail</title>
</head>
<body>
    <h1>Developer Detail</h1>
    <p>Name: {{ programmer.name }}</p>
    <p>Surname: {{ programmer.surname }}</p>
    <p>Age: {{ programmer.age }}</p>
    <p>Language: {{ programmer.language }}</p>
    <p>Framework: {{ programmer.framework }}</p>
    <p>Experience: {{ programmer.experience }} years</p>
    <a href="{% url 'developers:developer_list' %}">Back to Developer List</a>
</body>
</html>

portfolio_/developers/templates/developers/developer_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Developers List</title>
</head>
<body>
    <h1>Developers List</h1>
    <ul>
        {% for programmer in programmers %}
            <li><a href="{% url 'developers:developer_detail' programmer.pk %}">{{ programmer.name }} {{ programmer.surname }}</a></li>
        {% endfor %}
    </ul>
    <a href="{% url 'developers:add_developer'  %}">Add New Developer</a>
</body>
</html>